In [5]:
from sklearn.feature_extraction import DictVectorizer #对字典数据进行向量化
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA
import jieba
import numpy as np
from sklearn.impute import SimpleImputer

特征列中含有字符串。如何做特征提取（当成类别）

In [17]:
dict1=DictVectorizer(sparse=True) #sparse=True 稀疏矩阵 二维矩阵很多都是0的时候，就可以用稀疏存储节约空间。缺点，所有机器学习都要转为四四方方的存储。
data=dict1.fit_transform([{'city':'北京','temperature':100},
                          {"city":"上海","temperature":60},
                          {"city":"深圳","temperature":70}])
#区分fit_transform和transform
# transform用于测试集 fit_transform用于训练集
# print(data)
print('-'*50)
print(dict1.get_feature_names_out()) #特征列
print('-'*50)
print(dict1.inverse_transform(data)) #逆转回去
# one-hot 独热码

--------------------------------------------------
['city=上海' 'city=北京' 'city=深圳' 'temperature']
--------------------------------------------------
[{'city=北京': np.float64(1.0), 'temperature': np.float64(100.0)}, {'city=上海': np.float64(1.0), 'temperature': np.float64(60.0)}, {'city=深圳': np.float64(1.0), 'temperature': np.float64(70.0)}]


文本处理，不可以用独热码，因为如果使用独热码，会让矩阵变得非常长 ，有多少样本，就有多少特征。

In [16]:
#统计词频，max_df,min_df 小数（0-1），某个词出现的次数/所有文档数量
#min_df=2
#默认会去除单个字母的单词。默认认为这个词对整个样本没有影响。认为其没有语义
vector1=CountVectorizer(min_df=2) #最小的词频是2，只统计大于等于2的，词频等于1的被过滤了，特征越多，训练越慢。
res=vector1.fit_transform(["life is short, i like python life",
                           "life is too long, i dislike python ",
                           "life is short"])
print(vector1.get_feature_names_out()) #特征列名字
print('-'*50)
print(res.toarray())
print('-'*50)
# print(res)

['is' 'life' 'python' 'short']
--------------------------------------------------
[[1 2 1 1]
 [1 1 1 0]
 [1 1 0 1]]
--------------------------------------------------


英文默认空格分隔，中文用jieba分词,词频代表一个文章，模型学习的是规律，如果一个词是“的”没有实际含义，但是每篇文章都有。会让模型误解，他很重要，但是他没有具体的含义。
tf-idf

In [ ]:
def tfdifvec():
    """
    中文特征值化，用于计算tfidf值
    tf 词的频率出现的次数
    idf逆文档频率
    log(总文档的数量/该词出现的文档数量)
    平滑处理：训练的时候有3个特征，测试的时候比如样本里没有这个词，总文档数/（测试集没有这个词的话，这里就是0），这里就会出现零分裂，加一个1，只是为了可计算
    :return:
    """
    tf=TfidfVectorizer(smooth_idf=True)# 做平滑处理，
    return  0
