In [8]:
from sklearn.feature_extraction import DictVectorizer #对字典数据进行向量化
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA
import jieba
import numpy as np
from sklearn.impute import SimpleImputer

特征列中含有字符串。如何做特征提取（当成类别）

In [ ]:
dict1=DictVectorizer(sparse=True) #sparse=True 稀疏矩阵 二维矩阵很多都是0的时候，就可以用稀疏存储节约空间。缺点，所有机器学习都要转为四四方方的存储。
data=dict1.fit_transform([{'city':'北京','temperature':100},
                          {"city":"上海","temperature":60},
                          {"city":"深圳","temperature":70}])
#区分fit_transform和transform
# transform用于测试集 fit_transform用于训练集
# print(data)
print('-'*50)
print(dict1.get_feature_names_out()) #特征列
print('-'*50)
print(dict1.inverse_transform(data)) #逆转回去
# one-hot 独热码

文本处理，不可以用独热码，因为如果使用独热码，会让矩阵变得非常长 ，有多少样本，就有多少特征。

In [ ]:
#统计词频，max_df,min_df 小数（0-1），某个词出现的次数/所有文档数量
#min_df=2
#默认会去除单个字母的单词。默认认为这个词对整个样本没有影响。认为其没有语义
vector1=CountVectorizer(min_df=2) #最小的词频是2，只统计大于等于2的，词频等于1的被过滤了，特征越多，训练越慢。
res=vector1.fit_transform(["life is short, i like python life",
                           "life is too long, i dislike python ",
                           "life is short"])
print(vector1.get_feature_names_out()) #特征列名字
print('-'*50)
print(res.toarray())
print('-'*50)
# print(res)

英文默认空格分隔，中文用jieba分词

归一化的时候，马化腾一进来以后，其他人都是0，模型的分布就出问题了，这是异常值，归一化在有异常值的时候，效果是很差的，只有一个1，别的都是0.适合传统精确小数据场景。
四种异常值的处理手法。
标准化(x-均值)/标准差 可能会出现负值。
归一化和标准化是为了把不同特征拉到同一个量纲。如果每个人的财富一样，那么标准差是很小的。实际是变化为 均值为0，标准差为1。并不是标准正态分布。
标准化总结，对于异常值模型的稳定性不大。
归一化的时候，马化腾一进来以后，其他人都是0，模型的分布就出问题了，这是异常值，归一化在有异常值的时候，效果是很差的，只有一个1，别的都是0.适合传统精确小数据场景。
四种异常值的处理手法。
标准化(x-均值)/标准差 可能会出现负值。
归一化和标准化是为了把不同特征拉到同一个量纲。如果每个人的财富一样，那么标准差是很小的。实际是变化为 均值为0，标准差为1。并不是标准正态分布。
标准化总结，对于异常值模型的稳定性不大。

In [ ]:
std=StandardScaler()
data=std.fit_transform([[1,-1,3],[2,4,2],[4,6,-1]])#标准化
print(data)
print('-'*50)
print(std.mean_)
print('-'*50)
print(std.var_)
print('-'*50)

第二节课
降维
机器学习分类算法。（k近邻）

In [6]:
#特征选择原因 冗余。噪声。 两个特征，一个身高cm，一个个子高矮类别，没必要用两个。噪声，部分特征对预测结果又负影响
#特征选择太多，需要减少，三种方法 filter 过滤式 embedded嵌入式  wrapped包裹
# 删除方差为0（或者低方差的特征）特征的分布和目标值的分布，这列特征方差低，分布更多的是相同的，对最终的结果影响比较小。
# 还有一种是方差选择，把所有的特征列计算方差，把方差按照大小进行排列，删除方差小的，保留方差比较大的，因为方差小的话，对最终结果的影响比较小
def var():
    var=VarianceThreshold(threshold=0.6) #删除方差低于0.6的特征。方差阈值
    arr=[[0,2,0,3],[0,1,4,3],[0,1,1,3]]
    data=var.fit_transform(arr)
    print(var.get_support(True)) #查看保留了哪些特征列
    print(data)
    std=StandardScaler()
    d=std.fit_transform(arr)
    print(std.var_)
var()

[2]
[[0]
 [4]
 [1]]
[0.         0.22222222 2.88888889 0.        ]


标准化对异常值很宽容。
第二节课
降维
机器学习分类算法。（k近邻）



In [4]:
#特征选择原因 冗余。噪声。 两个特征，一个身高cm，一个个子高矮类别，没必要用两个。噪声，部分特征对预测结果又负影响
#特征选择太多，需要减少，三种方法 filter 过滤式 embedded嵌入式  wrapped包裹
# 删除方差为0（或者低方差的特征）特征的分布和目标值的分布，这列特征方差低，分布更多的是相同的，对最终的结果影响比较小。
# 还有一种是方差选择，把所有的特征列计算方差，把方差按照大小进行排列，删除方差小的，保留方差比较大的，因为方差小的话，对最终结果的影响比较小
def var():
    var=VarianceThreshold(threshold=0.6) #删除方差低于0.6的特征。方差阈值
    arr=[[0,2,0,3],[0,1,4,3],[0,1,1,3]]
    data=var.fit_transform(arr)
    print(var.get_support(True)) #查看保留了哪些特征列
    print(data)
    std=StandardScaler()
    d=std.fit_transform(arr)
    print(std.var_)
var()

[2]
[[0]
 [4]
 [1]]
[0.         0.22222222 2.88888889 0.        ]


In [5]:
std=StandardScaler()
data=std.fit_transform([[1,-1,3],[2,4,2],[4,6,-1]])#标准化
print(data)
print('-'*50)
print(std.mean_)
print('-'*50)
print(std.var_)
print('-'*50)

[[-1.06904497 -1.35873244  0.98058068]
 [-0.26726124  0.33968311  0.39223227]
 [ 1.33630621  1.01904933 -1.37281295]]
--------------------------------------------------
[2.33333333 3.         1.33333333]
--------------------------------------------------
[1.55555556 8.66666667 2.88888889]
--------------------------------------------------


pca降维 主成分分析，300维特征，降低到30维，不是和方差阈值一样直接删除特征
高维空间的点投影到低维空间。每个点到数轴的距离和最小。

In [ ]:
#pca降维，主成分分析
#高位空间降维到低维空间。
#n_components=0.9 主成分保留 原来的百分之90  方差和降维后会变大。降维降成计为，得到的每一列的方差和除以原有数据方差之和。

#n_components =整数，只保留几列特征
#一般是大于0.9 最后调成几是要看模型评估来判断。
# pca有时候会不稳定，特征很多，训练时间很长，可以尝试pca降维。如果发现效果很差，那就不要用降维。


模型切割为70% 30%用来做训练集和测试集，需要